#!/bin/bash

# Copy/paste this job script into a text file and submit with the command:
#    sbatch thefilename
# job standard output will go to the file slurm-%j.out (where %j is the job ID)

#SBATCH --time=00:15:00   # walltime limit (HH:MM:SS)
#SBATCH --nodes=1   # number of nodes
#SBATCH --ntasks-per-node=16       # number of cores
#SBATCH --partition=instruction    # class node(s)
#SBATCH --account=s2024.math.525.1    # account to use

# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE
module purge
module load intel
make
mpirun -np  1 ./main.exe 256000 > output.data
mpirun -np  2 ./main.exe 256000 >> output.data
mpirun -np  4 ./main.exe 256000 >> output.data
mpirun -np  8 ./main.exe 256000 >> output.data
mpirun -np 16 ./main.exe 256000 >> output.data
