#!/bin/bash


#SBATCH --time=00:01:00   # walltime limit (HH:MM:SS)
#SBATCH --nodes=1   # number of nodes
#SBATCH --ntasks-per-node=36   # 36 processor core(s) per node
#SBATCH --job-name="openmp"

# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE

module purge
module load gcc
make

./openmp_mc_pi.exe > mc_pi_table.txt
